### ISSUE TITLE
algorithm not supported

### ISSUE THREAD

**Issue by pandawankenobi** [snok/django-auth-adfs#164]
upon updating a docker build using your excellent package i got the error
AttributeError: module 'jwt' has no attribute 'ExpiredSignature'
I gathered that this might be a compatabilitiy issue, so i updated from 1.3.1 to 1.6.1.

Now when i deploy my application i get the errormessage  Algorithm not supported when logging in after recieving a jwt token,

**Comment by pandawankenobi** [comment]
i currently rolled back to the old docker container, and it still works with version 1.3.1. However if i build it again the same error occurs.

**Comment by JonasKs** [comment]
I need a full traceback, example config and so on. Impossible to help you without the entire picture.

**Comment by pandawankenobi** [comment]
Thats reasonable. 

Traceback:

2021-06-03T09:18:12.219566836Z Received authorization code: MYCODE
2021-06-03T09:18:12.219624236Z Getting access token at: https://adfs.MYWORKPLACE.dk/adfs/oauth2/token/
2021-06-03T09:18:12.289330844Z https://adfs.MYWORKPLACE.dk:443 "POST /adfs/oauth2/token/ HTTP/1.1" 200 26892
2021-06-03T09:18:12.296748434Z Received access token: MYTOKEN
2021-06-03T09:18:12.347153768Z Internal Server Error: /oauth2/callback
2021-06-03T09:18:12.347184568Z Traceback (most recent call last):
2021-06-03T09:18:12.347189768Z   File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 232, in _verify_signature
2021-06-03T09:18:12.347202668Z     alg_obj = self._algorithms[alg]
2021-06-03T09:18:12.347206568Z KeyError: 'RS256'
2021-06-03T09:18:12.347210068Z 
2021-06-03T09:18:12.347213668Z During handling of the above exception, another exception occurred:
2021-06-03T09:18:12.347217368Z 
2021-06-03T09:18:12.347220768Z Traceback (most recent call last):
2021-06-03T09:18:12.347224368Z   File "/usr/local/lib/python3.6/site-packages/django_auth_adfs/backend.py", line 69, in validate_access_token
2021-06-03T09:18:12.347228368Z     options=options,
2021-06-03T09:18:12.347231868Z   File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 119, in decode
2021-06-03T09:18:12.347235668Z     decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
2021-06-03T09:18:12.347239168Z   File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 95, in decode_complete
2021-06-03T09:18:12.347242968Z     **kwargs,
2021-06-03T09:18:12.347246368Z   File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 149, in decode_complete
2021-06-03T09:18:12.347249968Z     self._verify_signature(signing_input, header, signature, key, algorithms)
2021-06-03T09:18:12.347253468Z   File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 239, in _verify_signature
2021-06-03T09:18:12.347257168Z     raise InvalidAlgorithmError("Algorithm not supported")
2021-06-03T09:18:12.347260868Z jwt.exceptions.InvalidAlgorithmError: Algorithm not supported
2021-06-03T09:18:12.347301968Z 
2021-06-03T09:18:12.347305968Z During handling of the above exception, another exception occurred:
2021-06-03T09:18:12.347309568Z 
2021-06-03T09:18:12.347312868Z Traceback (most recent call last):
2021-06-03T09:18:12.347316268Z   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2021-06-03T09:18:12.347331368Z     response = get_response(request)
2021-06-03T09:18:12.347335368Z   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
2021-06-03T09:18:12.347339068Z     response = self.process_exception_by_middleware(e, request)
2021-06-03T09:18:12.347342568Z   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
2021-06-03T09:18:12.347346168Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2021-06-03T09:18:12.347349768Z   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
2021-06-03T09:18:12.347353468Z     return self.dispatch(request, *args, **kwargs)
2021-06-03T09:18:12.347356868Z   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
2021-06-03T09:18:12.347360468Z     return handler(request, *args, **kwargs)
2021-06-03T09:18:12.347364968Z   File "/usr/local/lib/python3.6/site-packages/django_auth_adfs/views.py", line 34, in get
2021-06-03T09:18:12.347368768Z     user = authenticate(request=request, authorization_code=code)
2021-06-03T09:18:12.347372168Z   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
2021-06-03T09:18:12.347376268Z     user = backend.authenticate(request, **credentials)
2021-06-03T09:18:12.347379768Z   File "/usr/local/lib/python3.6/site-packages/django_auth_adfs/backend.py", line 266, in authenticate
2021-06-03T09:18:12.347383368Z     user = self.process_access_token(access_token, adfs_response)
2021-06-03T09:18:12.347386868Z   File "/usr/local/lib/python3.6/site-packages/django_auth_adfs/backend.py", line 90, in process_access_token
2021-06-03T09:18:12.347390468Z     claims = self.validate_access_token(access_token)
2021-06-03T09:18:12.347393868Z   File "/usr/local/lib/python3.6/site-packages/django_auth_adfs/backend.py", line 71, in validate_access_token
2021-06-03T09:18:12.347397568Z     except jwt.ExpiredSignature as error:
2021-06-03T09:18:12.347400968Z AttributeError: module 'jwt' has no attribute 'ExpiredSignature'
2021-06-03T09:18:12.347404568Z [pid: 13|app: 0|req: 37/42] 172.16.3.1 () {86 vars in 3649 bytes} [Thu Jun  3 11:18:11 2021] GET /oauth2/callback?code=VnFBXpL06UmTFfrIeW4OFw.ZnhVgnAm2Qh_AaFb4zb4dmSTzl8.E9yTrvH7-N17p_Jv7EUjYdM0w3G5bBl1XRvO1Ft1TAUkDVGbfd8ettXO35Z1BkCl9PBgyn-nKBaeJsIGfWBT81GdI1F9cCyTC0bCqOLZKK0TFHSIXmF2prktCir4Cemic6qIpSzyFJeTorsSNiE4L8pAszOsj_g_jsv1lxaVOsMOXKayxfe6coNlBdJRrlvTjBvS6L4C19JeALRK92hRhzwflr1ab4U5nqmtYNK7nzMOPk7wDVYT7bfnXqTKunfFLIHNqBRg59xDfaRTdQ__K2z-XXtHrC72AwaWdvTb1rvoXBDdDv9RTtvPZoHbFjwohm4SJCD5ZMzbdWnRNss1ww&state=L3Zpa2FyL215Lw== => generated 27 bytes in 838 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 1)
2021-06-03T09:18:12.350466964Z 172.16.3.1 - - [03/Jun/2021:09:18:12 +0000] "GET /oauth2/callback?code=VnFBXpL06UmTFfrIeW4OFw.ZnhVgnAm2Qh_AaFb4zb4dmSTzl8.E9yTrvH7-N17p_Jv7EUjYdM0w3G5bBl1XRvO1Ft1TAUkDVGbfd8ettXO35Z1BkCl9PBgyn-nKBaeJsIGfWBT81GdI1F9cCyTC0bCqOLZKK0TFHSIXmF2prktCir4Cemic6qIpSzyFJeTorsSNiE4L8pAszOsj_g_jsv1lxaVOsMOXKayxfe6coNlBdJRrlvTjBvS6L4C19JeALRK92hRhzwflr1ab4U5nqmtYNK7nzMOPk7wDVYT7bfnXqTKunfFLIHNqBRg59xDfaRTdQ__K2z-XXtHrC72AwaWdvTb1rvoXBDdDv9RTtvPZoHbFjwohm4SJCD5ZMzbdWnRNss1ww&state=L3Zpa2FyL215Lw== HTTP/1.1" 500 27 "https://msovikar.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37" "80.208.79.217:2229"
2021-06-03T09:18:12.428659661Z https://sentry.io:443 "POST /api/1401487/store/ HTTP/1.1" 200 41

**Comment by pandawankenobi** [comment]
Relevant piece of django settings

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "django_auth_adfs.backend.AdfsAuthCodeBackend",
)
INSTALLED_APPS.append("django_auth_adfs")


AUTH_ADFS = {
    "SERVER": "adfs.MYWORK.dk",
    "CLIENT_ID": "CLIENTID",
    "RELYING_PARTY_ID": "RELAYID",
    "AUDIENCE": "microsoft:identityserver:secretID",
    "CLAIM_MAPPING": {
        "first_name": "given_name",
        "last_name": "family_name",
        "email": "email",
    },
    "USERNAME_CLAIM": "winaccountname",
    "GROUPS_CLAIM": "group",
    "MIRROR_GROUPS": False, 
    "TIMEOUT": 5,
    "RETRIES": 24,
}

**Comment by pandawankenobi** [comment]
i hope that is sufficient. Thx for getting back to me!

**Comment by JonasKs** [comment]
Hi, sorry for taking time to get back at you.

This line: 
```` 
2021-06-03T09:18:12.347400968Z AttributeError: module 'jwt' has no attribute 'ExpiredSignature'
```` 

relates to #118. 

Are your `pyjwt` package very old? Can you update it?  
[Relevant comment](https://github.com/snok/django-auth-adfs/pull/120#discussion_r558091914).

**Comment by pandawankenobi** [comment]
i will try it out. for now i'm closing the issue and expect it to work.
